general:
  productiveBranch: 'main'
  collectTelemetryData: false
  xMake:
    buildQuality: 'Milestone'
    novaCredentialsId: 'xmakeNova'
  maven:
    projectSettingsFile: '.pipeline/settings.xml'
  gitCredentialsId: 'SHA256:IXIvax2XosAQi9monapSa6Ys0pLgx/k74EOYuaPQ7zM'
  gitSshKeyCredentialsId: 'SHA256:IXIvax2XosAQi9monapSa6Ys0pLgx/k74EOYuaPQ7zM '
  buildTool: 'maven'

steps:
  dockerExecuteOnKubernetes:
    containerPullImageFlags:
      's4sdk/docker-node-browsers': true

  mavenExecute:
    dockerImage: maven:3.6.3-jdk-11-slim

artifactPrepareVersion:
  versioningType: 'cloud'
  gitSshKeyCredentialsId: 'SHA256:IXIvax2XosAQi9monapSa6Ys0pLgx/k74EOYuaPQ7zM'

mavenBuild:
  script: this
  buildTarget: 'CF'

nexusUpload:
  script: this
  url: http://artefact.focus.com.tn:8081/repository/
  nexus:
    nexusCredentialsId: 'nexus_manvenuser'

cloudFoundryDeploy:
  cloudFoundry:
    org: '2b1f4fe8trial'
    space: 'dev'
    credentialsId: 'null'
    #org: 4612c178trial
    #space: Focus Corporation
    #credentialsId: CF_Suser

stages:
  frontendUnitTests:
    dockerImage: ppiper/node-browsers

  frontendIntegrationTests:
    dockerImage: ppiper/node-browsers

postActions:
  sendNotification:
    skipFeatureBranches: false
